version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map the host port to the container port
    volumes:
      - .:/usr/src/app # Bind mount for live reloading during development (optional)

